/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package subpanel;

import gui.Dashboard;
import gui.ReturnManagement;
import gui.SignIn;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author daham
 */
public class invoiceItemView extends javax.swing.JFrame {

    private ReturnManagement returnManagement;
    private Dashboard dashboard;
    
    String inid;

    public void setreturnManagement(ReturnManagement returnManagement) {
      
        this.returnManagement = returnManagement;
    }
    
    public void setDashboard(Dashboard dashboard){
        this.dashboard = dashboard;
    }
     
    /**
     * Creates new form invoiceItemView
     */
    public invoiceItemView() {
        initComponents();
        loadInvoiceItemProduct(inid);
    }

    public void loadInvoiceItemProduct(String inid) {
        try {
            ResultSet customerReturnResultSet = MySQL.execute("SELECT * FROM `invoice_item`"
                    + "INNER JOIN `invoice`\n"
                    + "ON `invoice`.`in_id`= `invoice_item`.`in_id`\n"
                    + "INNER JOIN `stock`\n"
                    + "ON `stock`.`barcode` = `invoice_item`.`st_barcode`\n"
                    + "INNER JOIN `size`\n"
                    + "ON `size`.`s_id` = `stock`.`s_id`\n"
                    + "INNER JOIN `color`\n"
                    + "ON `color`.`co_id` = `stock`.`co_id`\n"
                    + "INNER JOIN `product` \n"
                    + "ON `product`.p_id = `stock`.`p_id`"
                    + "WHERE `invoice_item`.`in_id` ='"+inid+"'");

            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            model.setRowCount(0);

            while (customerReturnResultSet.next()) {
                String invoiceItemId = customerReturnResultSet.getString("init_id");
                String stockBarcode = customerReturnResultSet.getString("barcode");
                String productTitle = customerReturnResultSet.getString("title");
                String size = customerReturnResultSet.getString("s_name");
                String color = customerReturnResultSet.getString("co_name");
                String quantity = customerReturnResultSet.getString("qty");

                Vector vector = new Vector();
                vector.add(invoiceItemId);
                vector.add(stockBarcode);
                vector.add(productTitle);
                vector.add(size);
                vector.add(color);
                vector.add(quantity);

                model.addRow(vector);
                jTable3.setModel(model);
            }

        } catch (Exception e) {
            SignIn.log1.warning(e.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setToolTipText("Title Bar");
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(27, 49, 77));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 117, 105));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Invoices Items");
        jLabel2.setPreferredSize(new java.awt.Dimension(109, 40));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Search");

        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField6.setPreferredSize(new java.awt.Dimension(249, 35));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/glass.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice Item ID", "Stock Barcode", "Product", "Size", "Color", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:

        int row = jTable3.getSelectedRow();

        if (evt.getClickCount() == 2 && jTable3.getSelectedRow() != -1) {

            String qty = String.valueOf(jTable3.getValueAt(row, 5));
            int initqty = Integer.parseInt(qty);
            if (initqty == 0) {
                JOptionPane.showMessageDialog(this, "Product Quantity Zero Can't Return Product", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (returnManagement != null) {
                returnManagement.getjFormattedTextField3().setText(String.valueOf(jTable3.getValueAt(row, 0)));
                returnManagement.getjTextField3().setText(String.valueOf(jTable3.getValueAt(row, 2)));
                returnManagement.getjFormattedTextField1().setText(String.valueOf(jTable3.getValueAt(row, 1)));
                returnManagement.getjTextField10().setText(String.valueOf(jTable3.getValueAt(row, 4)));
                returnManagement.getjFormattedTextField2().setText(String.valueOf(jTable3.getValueAt(row, 3)));
                dashboard.setEnabled(true);
                this.dispose();
            }
        }

    }//GEN-LAST:event_jTable3MouseClicked

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:

        String text = jTextField6.getText();

        try {
            ResultSet customerReturnResultSet = MySQL.execute("SELECT * FROM `invoice_item`"
                    + "INNER JOIN `invoice`\n"
                    + "ON `invoice`.`in_id`= `invoice_item`.`in_id`\n"
                    + "INNER JOIN `stock`\n"
                    + "ON `stock`.`barcode` = `invoice_item`.`st_barcode`\n"
                    + "INNER JOIN `size`\n"
                    + "ON `size`.`s_id` = `stock`.`s_id`\n"
                    + "INNER JOIN `color`\n"
                    + "ON `color`.`co_id` = `stock`.`co_id`\n"
                    + "INNER JOIN `product` \n"
                    + "ON `product`.p_id = `stock`.`p_id` "
                    + "WHERE `invoice_item`.`init_id` LIKE '%" + text + "%'"
                    + "OR `stock`.`barcode` LIKE '%" + text + "%'"
                    + "OR  `product`.`title` LIKE '%" + text + "%'");

            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            model.setRowCount(0);

            while (customerReturnResultSet.next()) {
                String invoiceItemId = customerReturnResultSet.getString("init_id");
                String stockBarcode = customerReturnResultSet.getString("barcode");
                String productTitle = customerReturnResultSet.getString("title");
                String size = customerReturnResultSet.getString("s_name");
                String color = customerReturnResultSet.getString("co_name");
                String quantity = customerReturnResultSet.getString("qty");

                Vector vector = new Vector();
                vector.add(invoiceItemId);
                vector.add(stockBarcode);
                vector.add(productTitle);
                vector.add(size);
                vector.add(color);
                vector.add(quantity);

                model.addRow(vector);
                jTable3.setModel(model);
            }

        } catch (Exception e) {
           SignIn.log1.warning(e.toString());
        }

    }//GEN-LAST:event_jTextField6KeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      dashboard.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField6;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
