/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ThinkPad
 */
public class StockManagement extends javax.swing.JPanel {

    /**
     * Creates new form StockManagement
     */
    public StockManagement() {
        initComponents();
        loadStock();
    }

    private void loadStock() {

        try {

            ResultSet stockResultSet = MySQL.execute("SELECT * FROM `stock` INNER JOIN `product`\n"
                    + "ON `stock`.`p_id` = `product`.`p_id`\n"
                    + "INNER JOIN `brand`\n"
                    + "ON `product`.`b_id` = `brand`.`b_id`\n"
                    + "INNER JOIN `category`\n"
                    + "ON `product`.`c_id` = `category`.`c_id`\n"
                    + "INNER JOIN `main_category`\n"
                    + "ON `main_category`.mc_id = `category`.`mc_id`\n"
                    + "INNER JOIN `size`\n"
                    + "ON `size`.`s_id` = `stock`.`s_id`\n"
                    + "INNER JOIN `color`\n"
                    + "ON `stock`.`co_id` = `color`.`co_id`"
                    + "INNER JOIN `grn_item`"
                    + "ON `grn_item`.`product_p_id`=`product`.`p_id`");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (stockResultSet.next()) {
                String stockBarcode = stockResultSet.getString("stock.barcode");
                String productId = stockResultSet.getString("product.p_id");
                String productTitle = stockResultSet.getString("product.title");
                String brandName = stockResultSet.getString("brand.b_name");
                String mainCategory = stockResultSet.getString("main_category.mc_name");
                String size = stockResultSet.getString("size.s_name");
                String colorName = stockResultSet.getString("color.co_name");
                String sellingprice = stockResultSet.getString("stock.price");
                String buying_price = stockResultSet.getString("grn_item.buying_price");
                String availableqty = stockResultSet.getString("stock.available_qty");

                Vector vector = new Vector();
                vector.add(stockBarcode);
                vector.add(productId);
                vector.add(productTitle);
                vector.add(brandName);
                vector.add(mainCategory);
                vector.add(size);
                vector.add(colorName);
                vector.add(sellingprice);
                vector.add(buying_price);
                vector.add(availableqty);

                model.addRow(vector);
                jTable1.setModel(model);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(980, 720));

        kGradientPanel1.setToolTipText("Title Bar");
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(27, 49, 77));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 117, 105));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user (8).png"))); // NOI18N
        jLabel1.setText("Stock Management");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jLabel1.setIconTextGap(10);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Search ");

        jTextField8.setPreferredSize(new java.awt.Dimension(249, 35));
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/glass.png"))); // NOI18N

        jButton1.setText("Print Stock Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("MIn :");

        jTextField5.setPreferredSize(new java.awt.Dimension(69, 35));

        jLabel17.setText("Max :");

        jTextField9.setPreferredSize(new java.awt.Dimension(69, 35));

        jLabel2.setBackground(new java.awt.Color(27, 49, 77));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Filter By Buying Price");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(136, 28));

        jButton2.setBackground(new java.awt.Color(27, 49, 77));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setText("Find");
        jButton2.setPreferredSize(new java.awt.Dimension(79, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("Min :");

        jTextField10.setPreferredSize(new java.awt.Dimension(69, 35));

        jLabel19.setText("Max :");

        jTextField11.setPreferredSize(new java.awt.Dimension(69, 35));

        jLabel5.setBackground(new java.awt.Color(118, 48, 129));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Filter By Selling Price");
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(136, 28));

        jButton3.setBackground(new java.awt.Color(27, 49, 77));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setText("Find");
        jButton3.setPreferredSize(new java.awt.Dimension(79, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setText("Min :");

        jTextField18.setPreferredSize(new java.awt.Dimension(69, 35));

        jLabel27.setText("Max :");

        jTextField19.setPreferredSize(new java.awt.Dimension(69, 35));

        jLabel7.setBackground(new java.awt.Color(0, 117, 105));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Filter By Quantity");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(136, 28));

        jButton5.setBackground(new java.awt.Color(27, 49, 77));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton5.setText("Find");
        jButton5.setPreferredSize(new java.awt.Dimension(79, 35));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock Barcode", "Product ID", "Product Title", "Brand", "Main Category", "Size", "Color", "Selling Price", "Buying Price", "Available Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String fromValue = jTextField5.getText();
        String toValue = jTextField9.getText();

        if (fromValue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter From Value", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (toValue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter To Value", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                ResultSet buyingPricers = MySQL.execute("SELECT * FROM `stock` INNER JOIN `product`\n"
                        + "ON `stock`.`p_id` = `product`.`p_id`\n"
                        + "INNER JOIN `brand`\n"
                        + "ON `product`.`b_id` = `brand`.`b_id`\n"
                        + "INNER JOIN `category`\n"
                        + "ON `product`.`c_id` = `category`.`c_id`\n"
                        + "INNER JOIN `main_category`\n"
                        + "ON `main_category`.mc_id = `category`.`mc_id`\n"
                        + "INNER JOIN `size`\n"
                        + "ON `size`.`s_id` = `stock`.`s_id`\n"
                        + "INNER JOIN `color`\n"
                        + "ON `stock`.`co_id` = `color`.`co_id`INNER JOIN `grn_item`\n"
                        + "ON `grn_item`.`product_p_id` = `product`.`p_id`\n"
                        + "WHERE `buying_price` BETWEEN '" + fromValue + "' AND '" + toValue + "'");

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                while (buyingPricers.next()) {
                    String stockBarcode = buyingPricers.getString("stock.barcode");
                    String productId = buyingPricers.getString("product.p_id");
                    String productTitle = buyingPricers.getString("product.title");
                    String brandName = buyingPricers.getString("brand.b_name");
                    String mainCategory = buyingPricers.getString("main_category.mc_name");
                    String size = buyingPricers.getString("size.s_name");
                    String colorName = buyingPricers.getString("color.co_name");
                    String price = buyingPricers.getString("stock.price");
                    String buyingprice = buyingPricers.getString("grn_item.buying_price");
                    String availableqty = buyingPricers.getString("stock.available_qty");

                    Vector vector = new Vector();
                    vector.add(stockBarcode);
                    vector.add(productId);
                    vector.add(productTitle);
                    vector.add(brandName);
                    vector.add(mainCategory);
                    vector.add(size);
                    vector.add(colorName);
                    vector.add(price);
                    vector.add(buyingprice);
                    vector.add(availableqty);

                    model.addRow(vector);
                    jTable1.setModel(model);
                }

                jTextField5.setText(" ");
                jTextField9.setText(" ");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:

        String search = jTextField8.getText();

        try {

            ResultSet stockSearchResultSet = MySQL.execute("SELECT * FROM `stock` INNER JOIN `product`\n"
                    + "ON `stock`.`p_id` = `product`.`p_id`\n"
                    + "INNER JOIN `brand`\n"
                    + "ON `product`.`b_id` = `brand`.`b_id`\n"
                    + "INNER JOIN `category`\n"
                    + "ON `product`.`c_id` = `category`.`c_id`\n"
                    + "INNER JOIN `main_category`\n"
                    + "ON `main_category`.mc_id = `category`.`mc_id`\n"
                    + "INNER JOIN `size`\n"
                    + "ON `size`.`s_id` = `stock`.`s_id`\n"
                    + "INNER JOIN `color`\n"
                    + "ON `stock`.`co_id` = `color`.`co_id` "
                    + "INNER JOIN `grn_item`"
                    + "ON `grn_item`.`product_p_id`=`product`.`p_id`"
                    + "WHERE `stock`.`barcode` LIKE'%" + search + "%' "
                    + "OR `product`.`title` LIKE '%" + search + "%'"
                    + "OR `brand`.`b_name` LIKE '%" + search + "%'"
                    + "OR `main_category`.`mc_name` LIKE '%" + search + "%'"
                    + "OR `size`.`s_name` LIKE '%" + search + "%' "
                    + "OR `color`.`co_name` LIKE '%" + search + "%'");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (stockSearchResultSet.next()) {
                String stockBarcode = stockSearchResultSet.getString("stock.barcode");
                String productId = stockSearchResultSet.getString("product.p_id");
                String productTitle = stockSearchResultSet.getString("product.title");
                String brandName = stockSearchResultSet.getString("brand.b_name");
                String mainCategory = stockSearchResultSet.getString("main_category.mc_name");
                String size = stockSearchResultSet.getString("size.s_name");
                String colorName = stockSearchResultSet.getString("color.co_name");
                String price = stockSearchResultSet.getString("stock.price");
                String buyingprice = stockSearchResultSet.getString("grn_item.buying_price");
                String availableqty = stockSearchResultSet.getString("stock.available_qty");

                Vector vector = new Vector();
                vector.add(stockBarcode);
                vector.add(productId);
                vector.add(productTitle);
                vector.add(brandName);
                vector.add(mainCategory);
                vector.add(size);
                vector.add(colorName);
                vector.add(price);
                vector.add(buyingprice);
                vector.add(availableqty);

                model.addRow(vector);
                jTable1.setModel(model);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String fromvalue = jTextField10.getText();
        String tovalue = jTextField11.getText();
        if (fromvalue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter From Value", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (tovalue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter To Value", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                ResultSet buyingPricers = MySQL.execute("SELECT * FROM `stock` INNER JOIN `product`\n"
                        + "ON `stock`.`p_id` = `product`.`p_id`\n"
                        + "INNER JOIN `brand`\n"
                        + "ON `product`.`b_id` = `brand`.`b_id`\n"
                        + "INNER JOIN `category`\n"
                        + "ON `product`.`c_id` = `category`.`c_id`\n"
                        + "INNER JOIN `main_category`\n"
                        + "ON `main_category`.mc_id = `category`.`mc_id`\n"
                        + "INNER JOIN `size`\n"
                        + "ON `size`.`s_id` = `stock`.`s_id`\n"
                        + "INNER JOIN `color`\n"
                        + "ON `stock`.`co_id` = `color`.`co_id`"
                        + "INNER JOIN `grn_item`"
                        + "ON `grn_item`.`product_p_id`=`product`.`p_id`"
                        + "WHERE `stock`.`price` BETWEEN '" + fromvalue + "' AND '" + tovalue + "'");

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                while (buyingPricers.next()) {
                    String stockBarcode = buyingPricers.getString("stock.barcode");
                    String productId = buyingPricers.getString("product.p_id");
                    String productTitle = buyingPricers.getString("product.title");
                    String brandName = buyingPricers.getString("brand.b_name");
                    String mainCategory = buyingPricers.getString("main_category.mc_name");
                    String size = buyingPricers.getString("size.s_name");
                    String colorName = buyingPricers.getString("color.co_name");
                    String price = buyingPricers.getString("stock.price");
                    String buyingprice = buyingPricers.getString("grn_item.buying_price");
                    String availableqty = buyingPricers.getString("stock.available_qty");

                    Vector vector = new Vector();
                    vector.add(stockBarcode);
                    vector.add(productId);
                    vector.add(productTitle);
                    vector.add(brandName);
                    vector.add(mainCategory);
                    vector.add(size);
                    vector.add(colorName);
                    vector.add(price);
                    vector.add(buyingprice);
                    vector.add(availableqty);

                    model.addRow(vector);
                    jTable1.setModel(model);
                }

                jTextField10.setText(" ");
                jTextField11.setText(" ");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        String fromqty = jTextField18.getText();
        String toqty = jTextField19.getText();

        if (fromqty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter From Value", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (toqty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter To Value", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                ResultSet buyingPricers = MySQL.execute("SELECT * FROM `stock` INNER JOIN `product`\n"
                        + "ON `stock`.`p_id` = `product`.`p_id`\n"
                        + "INNER JOIN `brand`\n"
                        + "ON `product`.`b_id` = `brand`.`b_id`\n"
                        + "INNER JOIN `category`\n"
                        + "ON `product`.`c_id` = `category`.`c_id`\n"
                        + "INNER JOIN `main_category`\n"
                        + "ON `main_category`.mc_id = `category`.`mc_id`\n"
                        + "INNER JOIN `size`\n"
                        + "ON `size`.`s_id` = `stock`.`s_id`\n"
                        + "INNER JOIN `color`\n"
                        + "ON `stock`.`co_id` = `color`.`co_id`"
                        + "INNER JOIN `grn_item`"
                        + "ON `grn_item`.`product_p_id`=`product`.`p_id`"
                        + "WHERE `stock`.`available_qty` BETWEEN '" + fromqty + "' AND '" + toqty + "'");

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                while (buyingPricers.next()) {
                    String stockBarcode = buyingPricers.getString("stock.barcode");
                    String productId = buyingPricers.getString("product.p_id");
                    String productTitle = buyingPricers.getString("product.title");
                    String brandName = buyingPricers.getString("brand.b_name");
                    String mainCategory = buyingPricers.getString("main_category.mc_name");
                    String size = buyingPricers.getString("size.s_name");
                    String colorName = buyingPricers.getString("color.co_name");
                    String price = buyingPricers.getString("stock.price");
                    String buying_price = buyingPricers.getString("grn_item.buying_price");
                    String availableqty = buyingPricers.getString("stock.available_qty");

                    Vector vector = new Vector();
                    vector.add(stockBarcode);
                    vector.add(productId);
                    vector.add(productTitle);
                    vector.add(brandName);
                    vector.add(mainCategory);
                    vector.add(size);
                    vector.add(colorName);
                    vector.add(price);
                    vector.add(buying_price);
                    vector.add(availableqty);

                    model.addRow(vector);
                    jTable1.setModel(model);
                }

                jTextField18.setText(" ");
                jTextField19.setText(" ");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            loadStock();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            HashMap<String, Object> map = new HashMap<>();
            String reportPath = "/reports/StockRep.jasper";
            JRDataSource datasource = new JRTableModelDataSource(jTable1.getModel());
            JasperPrint jasperPrint = JasperFillManager.fillReport(getClass().getResourceAsStream(reportPath), map, datasource);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            SignIn.log1.warning(e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
